version: "3.8"
services:
  postgres:
    image: postgres
    container_name: postgres-order-service
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: order
      POSTGRES_USER: ${POSTGRES_ROOT_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - ./postgres-order-service:/data/postgres
    restart: unless-stopped